import { REGISTRATION_ENDPOINT } from "./config";

export type UserSession={username:string;name:string;role:"admin"|"judge";token:string};
export type Student={name:string;age:number;gender:string;email:string};
export type Team={id:string;name:string;category:string;level:string;institution:string;province:string;district:string;director:string;institutionEmail:string;advisor:string;advisorRole:string;advisorGender:string;advisorPhone:string;advisorEmail:string;students:Student[];source:"web"|"excel"|"demo";createdAt:string};
export type Evaluation={id:string;createdAt:string;judge:string;judgeName:string;category:string;teamId:string;teamName:string;values:Record<string,string|number|boolean>;total:number|null;effectiveTime:number|null;notes:string;selected:boolean};
const EVALUATIONS_KEY="luva-demo-evaluations",SESSION_KEY="luva-session",TEAMS_KEY="luva-teams";
export const demoTeams:Team[]=[
 {id:"EQ-001",name:"RoboTicos",category:"seguidor",level:"Secundaria",institution:"Colegio Técnico Central",province:"San José",district:"Central",director:"Laura Mora",institutionEmail:"direccion@ctc.ed.cr",advisor:"Juan Pérez",advisorRole:"Docente",advisorGender:"Masculino",advisorPhone:"8888-1111",advisorEmail:"juan@ctc.ed.cr",students:[{name:"Daniel Rojas",age:14,gender:"Masculino",email:"daniel@example.com"},{name:"Sofía Mora",age:14,gender:"Femenino",email:"sofia@example.com"}],source:"demo",createdAt:new Date().toISOString()},
 {id:"EQ-002",name:"Circuit Masters",category:"electrotec",level:"Secundaria",institution:"Liceo Innovación",province:"Alajuela",district:"Central",director:"Mario Vega",institutionEmail:"direccion@liceo.ed.cr",advisor:"Ana Vega",advisorRole:"Asesora",advisorGender:"Femenino",advisorPhone:"8888-2222",advisorEmail:"ana@liceo.ed.cr",students:[{name:"Marco Solís",age:15,gender:"Masculino",email:"marco@example.com"}],source:"demo",createdAt:new Date().toISOString()},
 {id:"EQ-003",name:"NovaLab",category:"divulgacion",level:"Primaria II ciclo",institution:"Escuela Horizonte",province:"Cartago",district:"Oriental",director:"Elena Ruiz",institutionEmail:"direccion@horizonte.ed.cr",advisor:"Carlos Vargas",advisorRole:"Docente",advisorGender:"Masculino",advisorPhone:"8888-3333",advisorEmail:"carlos@horizonte.ed.cr",students:[{name:"Valeria Díaz",age:11,gender:"Femenino",email:"valeria@example.com"},{name:"Andrés León",age:12,gender:"Masculino",email:"andres@example.com"}],source:"demo",createdAt:new Date().toISOString()},
];
export function getTeams():Team[]{try{const saved=JSON.parse(localStorage.getItem(TEAMS_KEY)||"null");return Array.isArray(saved)?saved:demoTeams}catch{return demoTeams}}
export function saveTeams(teams:Team[]){localStorage.setItem(TEAMS_KEY,JSON.stringify(teams))}
export function addTeams(incoming:Team[]){const current=getTeams();const keys=new Set(current.map(t=>`${t.name}|${t.category}|${t.institution}`.toLowerCase()));const added=incoming.filter(t=>!keys.has(`${t.name}|${t.category}|${t.institution}`.toLowerCase()));saveTeams([...current,...added]);return{added:added.length,duplicates:incoming.length-added.length}}
async function api(payload:Record<string,unknown>){const endpoint=REGISTRATION_ENDPOINT;if(!endpoint)throw new Error("El servicio de acceso no está configurado.");const body=new URLSearchParams({payload:JSON.stringify(payload)}),response=await fetch(endpoint,{method:"POST",body});const result=await response.json();if(!result.ok)throw new Error(result.error||"No se pudo conectar con el servicio.");return result}
export async function login(username:string,password:string){const result=await api({action:"login",username,password});const session:UserSession={...result.user,token:result.token};sessionStorage.setItem(SESSION_KEY,JSON.stringify(session));if(Array.isArray(result.teams))saveTeams(result.teams);if(Array.isArray(result.evaluations))localStorage.setItem(EVALUATIONS_KEY,JSON.stringify(result.evaluations));return session}
export function getSession():UserSession|null{try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||"null")}catch{return null}}
export function logout(){const session=getSession();sessionStorage.removeItem(SESSION_KEY);if(session?.token)void api({action:"logout",token:session.token}).catch(()=>undefined)}
export function getEvaluations():Evaluation[]{try{return JSON.parse(localStorage.getItem(EVALUATIONS_KEY)||"[]")}catch{return[]}}
export async function saveEvaluation(e:Evaluation){const session=getSession();if(!session)throw new Error("Sesión inválida.");await api({action:"saveEvaluation",token:session.token,evaluation:e});const rows=getEvaluations();rows.push(e);localStorage.setItem(EVALUATIONS_KEY,JSON.stringify(rows))}
export function toggleSelected(id:string){const target=getEvaluations().find(r=>r.id===id);if(!target)return;localStorage.setItem(EVALUATIONS_KEY,JSON.stringify(getEvaluations().map(r=>r.teamId===target.teamId&&r.category===target.category?{...r,selected:r.id===id}:r)))}
