export type UserSession={username:string;name:string;role:"admin"|"judge"};
export type Student={name:string;age:number;gender:string;email:string};
export type Team={id:string;name:string;category:string;level:string;institution:string;province:string;district:string;director:string;institutionEmail:string;advisor:string;advisorRole:string;advisorGender:string;advisorPhone:string;advisorEmail:string;students:Student[];source:"web"|"excel"|"demo";createdAt:string};
export type Evaluation={id:string;createdAt:string;judge:string;judgeName:string;category:string;teamId:string;teamName:string;values:Record<string,string|number|boolean>;total:number|null;effectiveTime:number|null;notes:string;selected:boolean};
const EVALUATIONS_KEY="luva-demo-evaluations",SESSION_KEY="luva-session",TEAMS_KEY="luva-teams";
export const demoUsers=[{username:"admin",password:"Admin2026!",name:"Administrador LUVÁ",role:"admin" as const},{username:"juez.ana",password:"Juez2026!",name:"Ana Rodríguez",role:"judge" as const},{username:"juez.carlos",password:"Juez2026!",name:"Carlos Vargas",role:"judge" as const}];
export const demoTeams:Team[]=[
 {id:"EQ-001",name:"RoboTicos",category:"seguidor",level:"III Ciclo",institution:"Colegio Técnico Central",province:"San José",district:"Central",director:"Laura Mora",institutionEmail:"direccion@ctc.ed.cr",advisor:"Juan Pérez",advisorRole:"Docente",advisorGender:"Masculino",advisorPhone:"8888-1111",advisorEmail:"juan@ctc.ed.cr",students:[{name:"Daniel Rojas",age:14,gender:"Masculino",email:"daniel@example.com"},{name:"Sofía Mora",age:14,gender:"Femenino",email:"sofia@example.com"}],source:"demo",createdAt:new Date().toISOString()},
 {id:"EQ-002",name:"Circuit Masters",category:"electrotec",level:"III Ciclo",institution:"Liceo Innovación",province:"Alajuela",district:"Central",director:"Mario Vega",institutionEmail:"direccion@liceo.ed.cr",advisor:"Ana Vega",advisorRole:"Asesora",advisorGender:"Femenino",advisorPhone:"8888-2222",advisorEmail:"ana@liceo.ed.cr",students:[{name:"Marco Solís",age:15,gender:"Masculino",email:"marco@example.com"}],source:"demo",createdAt:new Date().toISOString()},
 {id:"EQ-003",name:"NovaLab",category:"divulgacion",level:"II Ciclo",institution:"Escuela Horizonte",province:"Cartago",district:"Oriental",director:"Elena Ruiz",institutionEmail:"direccion@horizonte.ed.cr",advisor:"Carlos Vargas",advisorRole:"Docente",advisorGender:"Masculino",advisorPhone:"8888-3333",advisorEmail:"carlos@horizonte.ed.cr",students:[{name:"Valeria Díaz",age:11,gender:"Femenino",email:"valeria@example.com"},{name:"Andrés León",age:12,gender:"Masculino",email:"andres@example.com"}],source:"demo",createdAt:new Date().toISOString()},
];
export function getTeams():Team[]{try{const saved=JSON.parse(localStorage.getItem(TEAMS_KEY)||"null");return Array.isArray(saved)?saved:demoTeams}catch{return demoTeams}}
export function saveTeams(teams:Team[]){localStorage.setItem(TEAMS_KEY,JSON.stringify(teams))}
export function addTeams(incoming:Team[]){const current=getTeams();const keys=new Set(current.map(t=>`${t.name}|${t.category}|${t.institution}`.toLowerCase()));const added=incoming.filter(t=>!keys.has(`${t.name}|${t.category}|${t.institution}`.toLowerCase()));saveTeams([...current,...added]);return{added:added.length,duplicates:incoming.length-added.length}}
export function login(username:string,password:string){const user=demoUsers.find(u=>u.username.toLowerCase()===username.trim().toLowerCase()&&u.password===password);if(!user)return null;const session:UserSession={username:user.username,name:user.name,role:user.role};sessionStorage.setItem(SESSION_KEY,JSON.stringify(session));return session}
export function getSession():UserSession|null{try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||"null")}catch{return null}}
export function logout(){sessionStorage.removeItem(SESSION_KEY)}
export function getEvaluations():Evaluation[]{try{return JSON.parse(localStorage.getItem(EVALUATIONS_KEY)||"[]")}catch{return[]}}
export function saveEvaluation(e:Evaluation){const rows=getEvaluations();rows.push(e);localStorage.setItem(EVALUATIONS_KEY,JSON.stringify(rows))}
export function toggleSelected(id:string){const target=getEvaluations().find(r=>r.id===id);if(!target)return;localStorage.setItem(EVALUATIONS_KEY,JSON.stringify(getEvaluations().map(r=>r.teamId===target.teamId&&r.category===target.category?{...r,selected:r.id===id}:r)))}
